// Shared Tailwind theme (design tokens) for the memorial site. Included by
// index.html, gallery.html, sections.html, and letters.html so the palette,
// radii, and font stack stay a single source of truth instead of being
// duplicated per page.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c19",
        "primary-container": "#1a2e44",
        "on-primary-container": "#8296b0",
        "on-tertiary-fixed-variant": "#504536",
        "on-tertiary-fixed": "#231a0e",
        "surface-container-highest": "#ccd1d6",
        "on-error-container": "#93000a",
        "surface-container-low": "#e6e9ec",
        "tertiary-fixed-dim": "#d5c4b1",
        "on-secondary-container": "#5e656c",
        outline: "#74777d",
        "on-surface-variant": "#43474d",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#dce3eb",
        error: "#ba1a1a",
        "surface-dim": "#c7ccd1",
        "on-primary-fixed-variant": "#35485f",
        "primary-fixed-dim": "#b4c8e4",
        "surface-tint": "#4c6078",
        "on-background": "#1b1c19",
        "inverse-primary": "#b4c8e4",
        "on-secondary-fixed": "#161c22",
        "on-error": "#ffffff",
        "surface-container": "#e1e4e8",
        "surface-bright": "#eef0f2",
        tertiary: "#1f170b",
        "on-tertiary-container": "#a19280",
        "surface-variant": "#e4e2dd",
        surface: "#eef0f2",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#f1e0cc",
        "inverse-surface": "#30312e",
        primary: "#1A2E44", // Navy from Eternal Grace
        "primary-fixed": "#d1e4ff",
        "inverse-on-surface": "#f2f1ec",
        "error-container": "#ffdad6",
        "tertiary-container": "#352b1e",
        "on-secondary": "#ffffff",
        "surface-container-high": "#d9dce1",
        "on-primary-fixed": "#061d32",
        "on-secondary-fixed-variant": "#41484e",
        "on-tertiary": "#ffffff",
        background: "#eef0f2", // Cool slate-grey (was warm cream)
        "secondary-fixed": "#dce3eb",
        "outline-variant": "#c4c6cd",
        "secondary-fixed-dim": "#c0c7ce",
        secondary: "#585f65",
        "accent-gold": "#7C8CA0", // Dusty slate-blue (was gold)
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        serif: ["Assistant", "sans-serif"],
        sans: ["Assistant", "sans-serif"],
        headline: ["Assistant", "sans-serif"],
        body: ["Assistant", "sans-serif"],
        label: ["Assistant", "sans-serif"],
      },
    },
  },
};
